### ISSUE TITLE
route state resolve calling once

### ISSUE THREAD

**Issue by djindjic** [gocardless/angularjs-style-guide#25]
https://github.com/gocardless/angularjs-style-guide#use-resolvers-to-inject-data
does it blocks you to see modified data after first page load? or you are using some trick to  get resolve calling again?

I found [this](http://stackoverflow.com/questions/22730868/ui-routers-resolve-functions-are-only-called-once) stackoverflow solution, but it is interesting for me to hear how you do it?

**Comment by harrison** [comment]
Ah yeah we use `$state.reload()` or `$state.go('state', null, { reload: true });` for this (e.g. when in a modal and going back to the underlying page).
