### ISSUE TITLE
Where should I put angular.filter ?

### ISSUE THREAD

**Issue by phizaz** [gocardless/angularjs-style-guide#28]
I personally think that I should always use global filter, put it globally, not locally.

Seems you didn't provide where I should put it, should it be in `/helpers` ? on anywhere else ?

**Comment by harrison** [comment]
Yes, we put our filters in `/helpers`, we try and use everything as if it was local even though it's globally available in the app. This makes testing much easier as you don't need to remember to load any global modules in your spec setup.
